modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/quattage/mechano/issues"
license="LGPL v3"

[[mods]]
modId="mechano"
version="${file.jarVersion}"
displayName="Mechano"
#updateJSONURL=""
displayURL="https://discord.gg/2HBUz75Dg6"
logoFile="logo.png"
credits='''
Jake - Logos.
happygill - Code assistance
Special thanks to the Create team!'''
authors="quattage"
description='''
Bringing Create polish to other mods.'''

[[dependencies.mechano]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mechano]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mechano]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.e,0.5.2)"
    ordering="NONE"
    side="BOTH"